baseURL = 'https://leodamsky.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'
publishdir = "./public/"

[[menu.main]]
name = "Articles"
weight = 100
identifier = "articles"
url = "/content"
