baseURL = 'https://leodamsky.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'
publishdir = "./public/"

[[menu.main]]
name = "Posts"
weight = 100
identifier = "posts"
url = "/posts"

[[menu.main]]
name = "Tags"
weight = 100
identifier = "tags"
url = "/tags"
